### ISSUE TITLE
Use XF Users profile instead of using [tl] Profile Cover add-ons

### ISSUE THREAD

**Issue by TylerAustin7** [luutruong/XF2_Api#11]
I have xenforo 2.2.9 installed on my website and I don’t understand why we had to use this 
[tl] Profile Cover to use upload profile cover because the xenforo stuff have added this feature in xenforo 2.2

please use XF Profile cover instead of using [tl] Profile Cover for xenforo 2.2 or higher

**Comment by luutruong** [comment]
It's related to the app. Please make your suggestion here: https://nobita.me/forums/mobile-apps-suggestions/
