### ISSUE TITLE
MySQL query error [1071]: Specified key was too long

### ISSUE THREAD

**Issue by madfresh** [luutruong/XF2_Api#3]
![image](https://user-images.githubusercontent.com/50768409/83824939-8146b000-a6e0-11ea-8f59-adc7643bbed6.png)

**Comment by madfresh** [comment]
XF\Db\InvalidQueryException: xf_tapi_subscription: MySQL query error [1071]: Specified key was too long; max key length is 767 bytes in src/XF/Db/AbstractStatement.php at line 228
XF\Db\AbstractStatement->getException() in src/XF/Db/Mysqli/Statement.php at line 196
XF\Db\Mysqli\Statement->getException() in src/XF/Db/Mysqli/Statement.php at line 77
XF\Db\Mysqli\Statement->execute() in src/XF/Db/AbstractAdapter.php at line 94
XF\Db\AbstractAdapter->query() in src/XF/Db/Schema/AbstractDdl.php at line 151
XF\Db\Schema\AbstractDdl->apply() in src/XF/Db/SchemaManager.php at line 149
XF\Db\SchemaManager->alterTable() in src/addons/Truonglv/Api/DevHelper/SetupTrait.php at line 48
Truonglv\Api\Setup->doAlterTables() in src/addons/Truonglv/Api/Setup.php at line 23
Truonglv\Api\Setup->installStep1() in src/XF/AddOn/StepRunnerInstallTrait.php at line 60
Truonglv\Api\Setup->installStepRunner() in src/XF/AddOn/StepRunnerInstallTrait.php at line 27
Truonglv\Api\Setup->install() in src/XF/Admin/Controller/AddOn.php at line 398
XF\Admin\Controller\AddOn->actionInstall() in src/XF/Mvc/Dispatcher.php at line 350
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 257
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 113
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 55
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2190
XF\App->run() in src/XF.php at line 391
XF::runApp() in admin.php at line 13

**Comment by luutruong** [comment]
Look like you have used old mysql version. Please upgrade to latest version.
