### ISSUE TITLE
Add support for xenforo resources manager and xenforo media gallery

### ISSUE THREAD

**Issue by TylerAustin7** [luutruong/XF2_Api#6]
Can you please add support for xenforo resources manager and xenforo media gallery

**Comment by luutruong** [comment]
It's already supported by XFRM and XFMG.

**Comment by TylerAustin7** [comment]
I am using the mobile app but I don’t see a support for XFRM and XFMG in the mobile app

can you please tell me what’s do you mean?

**Comment by luutruong** [comment]
I mean the add-on XFRM and XFMG have it own api document.

**Comment by TylerAustin7** [comment]
Ok can you please add all features in xfrm and xfmg not just api

like users can download resources, creating resources, sharing media and others

I wanted all features from web to mobile app

**Comment by TylerAustin7** [comment]
P.S I don’t wanted my app to be low school coding. I wanted my app to be App Store edition choice not very limited features compared to themehouse app and web 🙁
